<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE object [
	<!ELEMENT object (trans,dao,service,proxy,action)>
	<!ELEMENT trans (bean)>
	<!ELEMENT dao (bean*)>
	<!ELEMENT service (bean*)>
	<!ELEMENT proxy (bean*)>
	<!ELEMENT action (bean*)>
	<!ELEMENT bean (property*) >
	<!ATTLIST bean id CDATA #REQUIRED>
	<!ATTLIST bean class CDATA #REQUIRED>
	<!ELEMENT property (#PCDATA)>
	<!ATTLIST property id CDATA #REQUIRED>
	<!ATTLIST property ref CDATA #REQUIRED>
]>
<object>
	<trans>
		<bean id="trans" class="com.web.trans.impl.TransactionImpl"></bean>
	</trans>
	<dao>
		<bean id="userDao" class="com.web.dao.impl.UserDaoImpl"></bean>
		<bean id="deptDao" class="com.web.dao.impl.DeptDaoImpl"></bean>
		<bean id="employeeDao" class="com.web.dao.impl.EmployeeDaoImpl"/>
		<bean id="holidayDao" class="com.web.dao.impl.HolidayDaoImpl"></bean>
		<bean id="accountDao" class="com.web.dao.impl.AccountDaoImpl"></bean>
		<bean id="roleDao" class="com.web.dao.impl.RoleDaoImpl"></bean>
		<bean id="mergeDao" class="com.web.dao.impl.MergeDaoImpl"></bean>
		<bean id="expenseDao" class="com.web.dao.impl.ExpenseDaoImpl"></bean>

	</dao>
	<service>
		<bean id="userService" class="com.web.service.impl.UserServiceImpl">
			<property id="userDao" ref="userDao"/>
		</bean>
		<bean id="deptService" class="com.web.service.impl.DeptServiceImpl">
			<property id="deptDao" ref="deptDao"/>
			<property id="employeeDao" ref="employeeDao"/>
		</bean>
		<bean id="employeeService" class="com.web.service.impl.EmployeeServiceImpl">
			<property id="employeeDao" ref="employeeDao"/>
			<property id="deptDao" ref="deptDao"/>
			<property id="holidayDao" ref="holidayDao"/>
			<property id="accountDao" ref="accountDao"/>
			<property id="expenseDao" ref="expenseDao"/>
			<property id="userDao" ref="userDao"/>
		</bean>
		
		<bean id="holidayService" class="com.web.service.impl.HolidayServiceImpl">
			<property id="holidayDao" ref="holidayDao"/>
			<property id="employeeDao" ref="employeeDao"/>
		</bean>
		<bean id="accountService" class="com.web.service.impl.AccountServiceImpl">
			<property id="accountDao" ref="accountDao"/>
		</bean>
		<bean id="roleService" class="com.web.service.impl.RoleServiceImpl">
			<property id="roleDao" ref="roleDao"/>
			<property id="accountDao" ref="accountDao"/>
		</bean>
		<bean id="mergeService" class="com.web.service.impl.MergeServiceImpl">
			<property id="mergeDao" ref="mergeDao"/>
		</bean>
		<bean id="expenseService" class="com.web.service.impl.ExpenseServiceImpl">
			<property id="expenseDao" ref="expenseDao"/>
			<property id="employeeDao" ref="employeeDao"/>
		</bean>
	</service>
	
	<proxy>
		<bean id="userServiceProxy" class="com.web.service.proxy.UserServiceProxy">
			<property id="userService" ref="userService"/>
			<!-- id指的是本类中对象的名字，ref指向目标bean -->
			<property id="trans" ref="trans"/>
		</bean>
		<bean id="deptServiceProxy" class="com.web.service.proxy.DeptServiceProxy">
			<property id="deptService" ref="deptService"/>
			<!-- id指的是本类中对象的名字，ref指向目标bean -->
			<property id="trans" ref="trans"/>
		</bean>
		<bean id="employeeServiceProxy" class="com.web.service.proxy.EmployeeServiceProxy">
		<property id="employeeService" ref="employeeService"/>
			<property id="trans" ref="trans"/>
		</bean>
		<bean id="holidayServiceProxy" class="com.web.service.proxy.HolidayServiceProxy">
		<property id="holidayService" ref="holidayService"/>
			<property id="trans" ref="trans"/>
		</bean>
		<bean id="accountServiceProxy" class="com.web.service.proxy.AccountServiceProxy">
		<property id="accountService" ref="accountService"/>
			<property id="trans" ref="trans"/>
		</bean>
		<bean id="roleServiceProxy" class="com.web.service.proxy.RoleServiceProxy">
		<property id="roleService" ref="roleService"/>
			<property id="trans" ref="trans"/>
		</bean>
		<bean id="mergeServiceProxy" class="com.web.service.proxy.MergeServiceProxy">
		<property id="mergeService" ref="mergeService"/>
			<property id="trans" ref="trans"/>
		</bean>
		<bean id="expenseServiceProxy" class="com.web.service.proxy.ExpenseServiceProxy">
		<property id="expenseService" ref="expenseService"/>
			<property id="trans" ref="trans"/>
		</bean>
	</proxy>
	
	<action>
		<bean id="userAction" class="com.web.action.UserAction">
			<property id="userService" ref="userServiceProxy"/>
			<property id="accountService" ref="accountServiceProxy"/>
		</bean>
		
		<bean id="deptAction" class="com.web.action.DeptAction">
			<property id="deptService" ref="deptServiceProxy"/>
			<property id="employeeService" ref="employeeServiceProxy"/>
		</bean>
		
		<bean id="employeeAction" class="com.web.action.EmployeeAction">
			<property id="employeeService" ref="employeeServiceProxy"/>
		</bean>
		<bean id="holidayAction" class="com.web.action.HolidayAction">
			<property id="holidayService" ref="holidayServiceProxy"/>
			<property id="accountService" ref="accountServiceProxy"/>
			<property id="mergeService" ref="mergeServiceProxy"/>
		</bean>
		<bean id="accountAction" class="com.web.action.AccountAction">
			<property id="accountService" ref="accountServiceProxy"/>
			<property id="employeeService" ref="employeeServiceProxy"/>
			<property id="userService" ref="userServiceProxy"/>
			
		</bean>
		<bean id="roleAction" class="com.web.action.RoleAction">
			<property id="roleService" ref="roleServiceProxy"/>
		</bean>
		<bean id="mergeAction" class="com.web.action.MergeAction">
			<property id="mergeService" ref="mergeServiceProxy"/>
			<property id="roleService" ref="roleServiceProxy"/>
			<property id="accountService" ref="accountServiceProxy"/>
		</bean>
		<bean id="expenseAction" class="com.web.action.ExpenseAction">
			<property id="expenseService" ref="expenseServiceProxy"/>
			<property id="employeeService" ref="employeeServiceProxy"/>
			<property id="accountService" ref="accountServiceProxy"/>
			<property id="mergeService" ref="mergeServiceProxy"/>
		</bean>
	</action>
</object>